name: Welcome Forkers

on:
  fork:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Send Welcome Message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues \
               -d '{"title": "Welcome!", "body": "Hi there! 👋 Thanks for forking this repository. We hope you enjoy exploring it!"}'
